export const UPDATING_PROFILE = 'UPDATING PROFILE';
export const UPDATING_PASSWORD = 'UPDATING PASSWORD';
export const UPDATING_SETTINGS = 'UPDATING SETTINGS';
export const REDIRECT_TO_REFERRER = 'REDIRECT TO REFERRER';
export const SET_PROFILE = 'SET PROFILE';
export const SET_REMINDER = 'SET REMINDER';
export const SET_SUMMARY = 'SET SUMMARY';
export const NOTIFICATION = 'SET NOTIFICATION';

export const DEFAULT_SIZE = 5;
